/**
 * This file was generated by the JPA Modeler
 */
package vo;

import DAO.EntidadeBase;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import utilitarios.Mask;

/**
 * @author Henrique
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "Entrada.BuscarTodos", query = "Select e from Entrada e ORDER BY(e.dt_entrada)"),
})
public class Entrada implements Serializable, EntidadeBase {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id_entrada;

    @Basic
    private int numero_nf;

    @Column(nullable = false)
    @Temporal(TemporalType.DATE)
    private Date dt_entrada;
    
    @Column(nullable = false)
    @Temporal(TemporalType.DATE)
    private Date dt_NF;

    public Date getDt_NF() {
        return dt_NF;
    }

    public void setDt_NF(Date dt_NF) {
        this.dt_NF = dt_NF;
    }

    @Column(scale = 8, precision = 2)
    private float valor_total;

    @ManyToOne(fetch = FetchType.EAGER)
    private Fornecedor id_fornecedor;

    @Override
    public Long getId() {
        return this.id_entrada;
    }

    public void setId_entrada(Long id_entrada) {
        this.id_entrada = id_entrada;
    }

    public int getNumero_nf() {
        return this.numero_nf;
    }

    public void setNumero_nf(int numero_nf) {
        this.numero_nf = numero_nf;
    }

    public Date getDt_entrada() {
        return this.dt_entrada;
    }

    public void setDt_entrada(Date dt_entrada) {
        this.dt_entrada = dt_entrada;
    }

    public float getValor_total() {
        return this.valor_total;
    }
    
    public String getValorTotalFormat(){
       String value=""+getValor_total();
        if (value.length() > 0) {
            int i = value.length();
            i = i - (value.indexOf("."));
            if (i == 2) {
                value += "0";
            }
        }
        Mask mask =new Mask();
        return mask.Monetaria(value);
    }

    public void setValor_total(float valor_total) {
        this.valor_total = valor_total;
    }

    public Fornecedor getId_fornecedor() {
        return id_fornecedor;
    }
    
    public String getDtNFFormat(){
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        return dt.format(dt_NF);
    }
    
    public String getDtEntradaFormat(){
         SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        return dt.format(dt_entrada);
    }
    
    public String getFornecedorNome(){
        return id_fornecedor.getRazao_social();
    }

    public void setId_fornecedor(Fornecedor id_fornecedor) {
        this.id_fornecedor = id_fornecedor;
    }

}
